---
- name: Check existing nginx
  become: yes
  shell: nginx -v
  register: existNginx
  ignore_errors: yes

- name: Install software via apt
  become: yes
  apt:
    name: "{{ additional_packages }}"
    force: yes
    state: latest
  when: existNginx.rc != 0

- name: Make sure nginx is enabled and restarted
  become: yes
  service:
    name: nginx
    state: restarted 
    enabled: yes 

- name: Nginx - Reboot server
  shell: "sleep 5 && reboot"
  async: 1
  poll: 0
  when: reboot_system

- name: Nginx - Wait for reboot
  wait_for_connection:
    connect_timeout: 10
    sleep: 2
    delay: 3
    timeout: 300
  when: reboot_system
