---
- name: Check existing nginx
  become: yes
  shell: nginx -v
  register: existNginx
  ignore_errors: yes

- name: Remove nginx-common
  become: yes
  apt:
    name: "nginx nginx-common"
    force: yes
    purge: yes
    state: absent

- name: Install software via apt
  become: yes
  apt:
    name: "{{ additional_packages }}"
    force: yes
  when: existNginx.rc != 0

- name: Delete default sites-available
  become: yes
  file: path=/etc/nginx/sites-available state=absent

- name: Delete default sites-enabled
  become: yes
  file: path=/etc/nginx/sites-enabled state=absent

- name: Fill /etc/nginx/nginx.conf with template
  become: yes
  template: src=nginx.conf dest=/etc/nginx/nginx.conf owner=root group=root mode=0644

- name: Fill /etc/nginx/conf.d/front.conf with template
  become: yes
  template: src=front.conf dest=/etc/nginx/conf.d/front.conf owner=root group=root mode=0644

- name: Make sure nginx is enabled and restarted
  become: yes
  service:
    name: nginx
    state: restarted 
    enabled: yes 
