---
- name: Check existing influxdb
  become: yes
  shell: influxd -h
  register: existInfluxdb
  ignore_errors: yes

- name: Install software via apt
  become: yes
  apt:
    name: "{{ additional_packages }}"
    force: yes
  when: existInfluxdb.rc != 0

- name: Add collectd types db
  become: yes
  copy:
    src: collectdTypes.db
    dest: /var/collectdTypes.db
    owner: influxdb
    group: influxdb
    mode: 0777
  when: existInfluxdb.rc != 0

- name: Fill /etc/influxdb/influxdb.conf with template
  become: yes
  template:
    src: influxdb.conf
    dest: /etc/influxdb/influxdb.conf
    owner: root
    group: root
    mode: 0644
  when: existInfluxdb.rc != 0

  #TODO porque no reinicia?
- name: Crontab influx ensure reboot
  become: yes
  cron:
    name: "Influx ensure running"
    minute: "*"
    hour: "*"
    day: "*"
    month: "*"
    weekday: "*"
    job: "bash -c 'if [ -z $(ps aux | grep \"influxdb.conf\" | grep -v grep) ]; then systemctl start influxdb; fi >/dev/null 2>&1'"

- name: Make sure influxdb is enabled and restarted
  become: yes
  service:
    name: influxdb
    state: restarted 
    enabled: yes
  when: existInfluxdb.rc != 0
