---

- name: Check existing influxdb
  become: yes
  shell: influxd -h
  register: existInfluxdb
  ignore_errors: yes

- name: Install software via apt
  become: yes
  apt:
    name: "{{ additional_packages }}"
    force: yes
  when: existInfluxdb.rc != 0

- name: Add collectd types db
  become: yes
  copy:
    src: collectdTypes.db
    dest: /var/collectdTypes.db
    owner: influxdb
    group: influxdb
    mode: 0777
  when: existInfluxdb.rc != 0

- name: Fill /etc/influxdb/influxdb.conf with template
  become: yes
  template:
    src: influxdb.conf
    dest: /etc/influxdb/influxdb.conf
    owner: root
    group: root
    mode: 0644
  when: existInfluxdb.rc != 0

- name: Make sure influxdb is enabled and restarted
  become: yes
  service:
    name: influxdb
    state: restarted 
    enabled: yes 
  when: existInfluxdb.rc != 0

- name: Insert some data example
  shell: for i in `seq 1 10`;do echo "test,type=total value=${i}" | curl -s -i -XPOST 'http://localhost:8086/write?db={{ influx.db.name }}' --data-binary @-; sleep 1; done

- name: Influxdb - Reboot server
  shell: "sleep 5 && reboot"
  async: 1
  poll: 0
  when: reboot_system

- name: Influxdb - Wait for reboot
  wait_for_connection:
    connect_timeout: 10
    sleep: 2
    delay: 3
    timeout: 300
  when: reboot_system
