---
- name: Save raspberry password to file
  shell: echo "{{ piPass }}" > /home/pi/.piPass && chmod 644 /home/pi/.piPass && chown pi:pi /home/pi/.piPass
  when: piPass != ""

- name: Save gmail credentials to file
  shell: echo "{{ gmailUser }}" > /home/pi/.gmailUser && chmod 644 /home/pi/.gmailUser && chown pi:pi /home/pi/.gmailUser
  when: gmailUser != ""

- name: Check grafana admin pass exists
  become: yes
  shell: cat /home/pi/.grafanaAdminPass
  register: existGrafanaPass
  ignore_errors: yes

- name: Save grafana admin pass to file
  shell: openssl rand -base64 14 > /home/pi/.grafanaAdminPass && chmod 644 /home/pi/.grafanaAdminPass && chown pi:pi /home/pi/.grafanaAdminPass
  when: existGrafanaPass.rc != 0

- name: Save duckdns token to file
  shell: echo "{{ duckDnsToken }}" > /home/pi/.duckDnsToken && chmod 644 /home/pi/.duckDnsToken && chown pi:pi /home/pi/.duckDnsToken
  when: duckDnsToken != ""

- name: Save duckdns url to file
  shell: echo "{{ duckDnsUrl }}" > /home/pi/.duckDnsUrl && chmod 644 /home/pi/.duckDnsUrl && chown pi:pi /home/pi/.duckDnsUrl
  when: duckDnsUrl != ""

- name: Save opendata aemet api key to file
  shell: echo "{{ aemet_opendata_apikey }}" > /home/pi/.aemet_opendata_apikey && chmod 644 /home/pi/.aemet_opendata_apikey && chown pi:pi /home/pi/.aemet_opendata_apikey
  when: aemet_opendata_apikey != ""
