---
- name: Save raspberry password to file
  shell: echo "{{ piPass }}" > /home/pi/.piPass && chmod 644 /home/pi/.piPass && chown pi:pi /home/pi/.piPass
  when: piPass != ""

- name: Check grafana admin pass exists
  become: yes
  shell: cat /home/pi/.grafanaAdminPass
  register: existGrafanaPass
  ignore_errors: yes
  when: pi.hostname == "meteopi"

- name: Save grafana admin pass to file
  shell: openssl rand -base64 29 | tr -d "=+/" | cut -c1-14 > /home/pi/.grafanaAdminPass && chmod 644 /home/pi/.grafanaAdminPass && chown pi:pi /home/pi/.grafanaAdminPass
  when: pi.hostname == "meteopi" and existGrafanaPass.rc != 0

- name: Save duckdns token to file
  shell: echo "{{ duckDnsToken }}" > /home/pi/.duckDnsToken && chmod 644 /home/pi/.duckDnsToken && chown pi:pi /home/pi/.duckDnsToken
  when: pi.hostname == "meteopi" and duckDnsToken != ""

- name: Save duckdns url to file
  shell: echo "{{ duckDnsUrl }}" > /home/pi/.duckDnsUrl && chmod 644 /home/pi/.duckDnsUrl && chown pi:pi /home/pi/.duckDnsUrl
  when: pi.hostname == "meteopi" and duckDnsUrl != ""

- name: Save opendata aemet api key to file
  shell: echo "{{ aemet_opendata_apikey }}" > /home/pi/.aemet_opendata_apikey && chmod 644 /home/pi/.aemet_opendata_apikey && chown pi:pi /home/pi/.aemet_opendata_apikey
  when: pi.hostname == "meteopi" and aemet_opendata_apikey != ""
