---

- name: Check existing grafana
  become: yes
  shell: grafana-server -h
  register: existGrafana
  ignore_errors: yes

- name: Download grafana deb
  get_url:
    url: "{{ grafana.url }}/{{ grafana.deb }}"
    dest: /home/pi/{{ grafana.deb }}
    mode: 0644
    timeout: 60
  when: existGrafana.rc != 2

- name: Install grafana deb
  become: yes
  apt:
    deb: /home/pi/{{ grafana.deb }}
  when: existGrafana.rc != 2

- name: Delete grafana deb
  become: yes
  file:
    path: /home/pi/{{ grafana.deb }}
    state: absent
  when: existGrafana.rc != 2

- name: Fill /etc/grafana/grafana.ini with template
  become: yes
  template: src=grafana.ini dest=/etc/grafana/grafana.ini owner=root group=grafana mode=0640

- name: Make sure grafana-server is enabled and restarted
  become: yes
  service:
    name: grafana-server
    state: restarted 
    enabled: yes

- name: Link influxdb datasource
  shell: "sleep 10 && echo \"\" && curl 'http://admin:admin@{{ pi.network.ip }}:3000/api/datasources' -X POST -H 'Content-Type: application/json;charset=UTF-8' --data-binary '{\"name\":\"{{ influx.db.name }}\",\"type\":\"influxdb\",\"url\":\"http://{{ pi.network.ip }}:8086\",\"access\":\"proxy\",\"isDefault\":true,\"database\":\"{{ influx.db.name }}\"}'"
  when: existGrafana.rc != 2

- name: Setup dashboards load folder
  become: yes
  blockinfile:
    path: /etc/grafana/provisioning/dashboards/loadDashboardsFrom.yaml
    create: yes
    mode: 0640
    owner: root
    group: grafana
    block: |
        apiVersion: 1
        providers:
         - name: 'loadDashboardsFrom'
           orgId: 1
           folder: ''
           type: file
           options:
             path: {{ grafana.dashboards_folder }}

- name: Creates grafana load dashboards folder
  become: yes
  file:
    path: /var/lib/grafana/dashboards
    owner: root
    group: grafana
    mode: 0755
    state: directory

- name: Fill dashboards with template
  become: yes
  template:
    src: "{{ item }}.json"
    dest: "{{ grafana.dashboards_folder }}/{{ item }}.json"
    owner: root
    group: root
    mode: 0644
  with_items:
    - piStatus
    - networkStatus
    - tests

- name: Fill home dashboard with template
  become: yes
  template:
    src: home.json
    dest: /usr/share/grafana/public/dashboards/home.json
    owner: root
    group: root
    mode: 0644

- name: Creates meteo-update-pictures folder
  become: yes
  file:
    path: "{{ grafana.meteoUpdatePicturesPath }}"
    owner: pi
    group: pi
    mode: 0755
    state: directory

- name: Creates meteo-update-pictures folder
  become: yes
  file:
    path: "{{ grafana.meteoUpdatePicturesPath }}"
    owner: pi
    group: pi
    mode: 0755
    state: directory

- name: Setup openaemet api key
  become: yes
  shell: echo {{ aemet_opendata_apikey }} > {{ grafana.meteoUpdatePicturesPath }}/api_key && chmod 644 {{ grafana.meteoUpdatePicturesPath }}/api_key && chown pi:pi {{ grafana.meteoUpdatePicturesPath }}/api_key 
  when: aemet_opendata_apikey != ""

- name: Setup meteo-update-pictures script
  template:
    src: updateMeteoPic.sh
    dest: "{{ grafana.meteoUpdatePicturesPath }}/updateMeteoPic.sh"
    mode: 0777

- name: Setup stop meteo-update-pictures script
  template:
    src: stopUpdateMeteoPic.sh
    dest: "{{ grafana.meteoUpdatePicturesPath }}/stopUpdateMeteoPic.sh"
    mode: 0777

- name: Stop meteo-update-pictures script
  become: yes
  shell: "{{ grafana.meteoUpdatePicturesPath }}/stopUpdateMeteoPic.sh"
  ignore_errors: yes

- name: Crontab meteo-update-pictures script
  cron:
    name: "UpdateMeteoPictures"
    minute: "*"
    hour: "*/6"
    day: "*"
    month: "*"
    weekday: "*" 
    job: "bash -c 'nohup {{ grafana.meteoUpdatePicturesPath }}/updateMeteoPic.sh &>> {{ grafana.meteoUpdatePicturesPath }}/updateMeteoPic.log&'"

- name: Create grafana admin credentials at lpass
  local_action: shell lpass generate --no-symbols --username admin --url={{duckDnsUrl}} {{ lpass.piId }}/grafanaAdmin 50
  register: grafanaPassAdmin
  when: existGrafana.rc != 2

- name: Change grafana admin password	
  shell: "curl -X PUT -H 'Content-Type: application/json' -d '{\"oldPassword\":\"admin\",\"newPassword\":\"{{ grafanaPassAdmin.stdout }}\",\"confirmNew\":\"{{ grafanaPassAdmin.stdout }}\"}' 'http://admin:admin@192.168.1.11:3000/api/user/password'"
  register: resultGrafanaPassAdmin
  failed_when: '"password changed" not in resultGrafanaPassAdmin.stdout'
  when: existGrafana.rc != 2

- name: Create grafana user credentials at lpass
  local_action: shell lpass generate --no-symbols --username read --url={{duckDnsUrl}} {{ lpass.piId }}/grafanaUser 50
  register: grafanaPassUser
  when: existGrafana.rc != 2

- name: Change grafana user password	
  shell: "curl -XPOST -H 'Content-Type: application/json' -d '{\"name\":\"read\",\"email\":\"{{ lookup('pipe', 'date +%s') }}@email.com\",\"login\":\"read\",\"password\":\"{{ grafanaPassUser.stdout }}\"}' 'http://admin:{{ grafanaPassAdmin.stdout }}@localhost:3000/api/admin/users'"
  register: resultGrafanaPassUser
  failed_when: '"ser created" not in resultGrafanaPassUser.stdout'
  when: existGrafana.rc != 2

- name: Re-Fill /etc/grafana/grafana.ini with template disallowing password changes via api.
  become: yes
  template: src=grafana_final.ini dest=/etc/grafana/grafana.ini owner=root group=grafana mode=0640

- name: Make sure grafana-server is enabled and restarted
  become: yes
  service:
    name: grafana-server
    state: restarted
