---

- name: Check existing grafana
  become: yes
  shell: grafana-server -h
  register: existGrafana
  ignore_errors: yes

- name: Install software via apt
  become: yes
  apt:
    deb: "{{ grafana.url }}/{{ grafana.deb }}"
  when: existGrafana.rc != 2

- name: Make sure grafana-server is enabled and restarted
  become: yes
  service:
    name: grafana-server
    state: restarted 
    enabled: yes
  when: existGrafana.rc != 2

- name: Link influxdb datasource
  shell: "sleep 10 && echo \"\" && curl 'http://admin:admin@localhost:3000/api/datasources' -X POST -H 'Content-Type: application/json;charset=UTF-8' --data-binary '{\"name\":\"{{ influx.db.name }}\",\"type\":\"influxdb\",\"url\":\"http://localhost:8086\",\"access\":\"proxy\",\"isDefault\":true,\"database\":\"{{ influx.db.name }}\"}'"
  when: existGrafana.rc != 2

- name: Fill /usr/share/grafana/public/default.json with template
  become: yes
  template:
    src: home.json
    dest: /usr/share/grafana/public/dashboards/home.json
    owner: root
    group: root
    mode: 0644
  when: existGrafana.rc != 2

- name: Grafana - Reboot server
  shell: "sleep 5 && reboot"
  async: 1
  poll: 0
  when: reboot_system

- name: Grafana - Wait for reboot
  wait_for_connection:
    connect_timeout: 10
    sleep: 2
    delay: 3
    timeout: 300
  when: reboot_system

