---

- name: Check existing grafana
  become: yes
  shell: grafana-server -h
  register: existGrafana
  ignore_errors: yes

- name: Download grafana deb
  get_url:
    url: "{{ grafana.url }}/{{ grafana.deb }}"
    dest: /home/pi/{{ grafana.deb }}
    mode: 0644
    timeout: 60
  when: existGrafana.rc != 2

- name: Install grafana deb
  become: yes
  apt:
    deb: /home/pi/{{ grafana.deb }}
  when: existGrafana.rc != 2

- name: Delete grafana deb
  become: yes
  file:
    path: /home/pi/{{ grafana.deb }}
    state: absent
  when: existGrafana.rc != 2

- name: Load gmail credentials from file
  shell: cat /home/pi/.gmailUser
  register: gmailUserReaded

- name: Load gmail password from file
  shell: cat /home/pi/.gmailPass
  register: gmailPassReaded

- name: Load duckDnsUrl from file
  shell: cat /home/pi/.duckDnsUrl
  register: duckDnsUrlReaded

- name: Fill /etc/grafana/grafana.ini with template
  become: yes
  template: src=grafana.ini dest=/etc/grafana/grafana.ini owner=root group=grafana mode=0640

- name: Make sure grafana-server is enabled and restarted
  become: yes
  service:
    name: grafana-server
    state: restarted 
    enabled: yes

- name: Link influxdb datasource
  shell: "sleep 15 && curl 'http://admin:admin@{{ pi.network.ip }}:3000/api/datasources' -X POST -H 'Content-Type: application/json;charset=UTF-8' --data-binary '{\"name\":\"{{ influx.db.name }}\",\"type\":\"influxdb\",\"url\":\"http://{{ pi.network.ip }}:8086\",\"access\":\"proxy\",\"isDefault\":true,\"database\":\"{{ influx.db.name }}\"}'"
  when: existGrafana.rc != 2

- name: Create grafana admin credentials at lpass
  local_action: shell lpass generate --no-symbols --username admin --url="{{ duckDnsUrlReaded.stdout }}" {{ lpass.piId }}/grafanaAdmin 50
  register: grafanaPassAdmin
  when: existGrafana.rc != 2

- name: Change grafana admin password	
  shell: "curl -X PUT -H 'Content-Type: application/json' -d '{\"oldPassword\":\"admin\",\"newPassword\":\"{{ grafanaPassAdmin.stdout }}\",\"confirmNew\":\"{{ grafanaPassAdmin.stdout }}\"}' 'http://admin:admin@192.168.1.11:3000/api/user/password'"
  register: resultGrafanaPassAdmin
  failed_when: '"changed" not in resultGrafanaPassAdmin.stdout'
  when: existGrafana.rc != 2

- name: Create grafana user credentials at lpass
  local_action: shell lpass generate --no-symbols --username read --url={{duckDnsUrlReaded.stdout }} {{ lpass.piId }}/grafanaUser 50
  register: grafanaPassUser
  when: existGrafana.rc != 2

- name: Change grafana user password	
  shell: "curl -XPOST -H 'Content-Type: application/json' -d '{\"name\":\"read\",\"email\":\"{{ lookup('pipe', 'date +%s') }}@email.com\",\"login\":\"read\",\"password\":\"{{ grafanaPassUser.stdout }}\"}' 'http://admin:{{ grafanaPassAdmin.stdout }}@localhost:3000/api/admin/users'"
  register: resultGrafanaPassUser
  failed_when: '"created" not in resultGrafanaPassUser.stdout'
  when: existGrafana.rc != 2

- name: Setup dashboards load folder
  become: yes
  blockinfile:
    path: /etc/grafana/provisioning/dashboards/loadDashboardsFrom.yaml
    create: yes
    mode: 0640
    owner: root
    group: grafana
    block: |
        apiVersion: 1
        providers:
         - name: 'loadDashboardsFrom'
           orgId: 1
           folder: ''
           type: file
           options:
             path: {{ grafana.dashboards_folder }}

- name: Creates grafana load dashboards folder
  become: yes
  file:
    path: /var/lib/grafana/dashboards
    owner: root
    group: grafana
    mode: 0755
    state: directory

- name: Fill dashboards with template
  become: yes
  template:
    src: "{{ item }}.json"
    dest: "{{ grafana.dashboards_folder }}/{{ item }}.json"
    owner: root
    group: root
    mode: 0644
  with_items:
    - piStatus
    - networkStatus

- name: Lastpass - Ensure user loged in
  local_action: shell lpass ls
  when: existGrafana.rc == 2

- name: Lastpass - Load credentials
  local_action: shell lpass show {{ lpass.piId }}/grafanaAdmin | grep username | awk '{print $2}'
  register: grafanaAdminUsername
  when: existGrafana.rc == 2

- name: Lastpass - Load password
  local_action: shell lpass show {{ lpass.piId }}/grafanaAdmin | grep password | awk '{print $2}'
  register: grafanaAdminPass
  when: existGrafana.rc == 2

- name: Create temp folder
  file:
    path: /tmp/temp
    mode: 0777
    state: directory
  when: existGrafana.rc == 2

- name: Setup create dashboards script
  template:
    src: create_faq.sh
    dest: "/tmp/temp/create_faq.sh"
    mode: 0777
  when: existGrafana.rc == 2

- name: Execute script
  shell: /tmp/temp/create_faq.sh
  when: existGrafana.rc == 2

- name: Delete temp folder
  file:
    path: /tmp/temp
    state: absent
  when: existGrafana.rc == 2

- name: Restart grafana-server
  become: yes 
  service:
    name: grafana-server
    state: restarted
