---
- hosts: meteopi
  remote_user: pi
  gather_facts: true
  vars_prompt:
  - name: advisor
    prompt: "\n\nCAUTION! This will re-password your raspberry pi at current lastpass logged in account.\n\n\nFollowing variable prompts will be stored as hidden files inside /home/pi folder.\nIf you have enter any of them before you don't need to do it again (simply press enter), unless you want to change it.\nPress enter to continue:"
    default: ""
    private: no

  - name: gmailUser
    prompt: "\n\nPlease type valid gmail account for emails sending from raspberry"
    default: ""
    private: no

  - name: gmailPass
    prompt: "\n\nNow, that gmail password."
    default: ""

  - name: duckDnsToken
    prompt: "\n\nInsert your DuckDns token present at http://www.duckdns.org"
    default: ""
    private: no

  - name: duckDnsUrl
    prompt: "\n\nWhat url have you chosen at duckdns? It's for lastpass auto-fill credentials"
    default: ""
    private: no

  - name: aemet_opendata_apikey
    prompt: "\n\nInsert your opendata aemet api key, if haven't yet go to https://opendata.aemet.es"
    default: ""
    private: no

  vars_files:
  - vars/piStuff.yaml

  roles:
    - firstTime
    - storeAccounts
    - common
    - security
    - duckDns
    - nginx
    - influxdb
    - metricsCollector
    - grafana
    - dht22
    - createMeteopiDash_Dht22
