---

- hosts: raspi
  remote_user: pi
  gather_facts: false
  vars_prompt:
  - name: gmailUser
    prompt: "\n\nValid gmail account for monit email alerts"
    private: no

  - name: gmailPass
    prompt: "\n\nType gmail password"

  - name: duckDnsToken
    prompt: "\n\nDuckDns token at http://www.duckdns.org"
    private: no

  vars_files:
  - vars/piStuff.yaml
  - vars/02-secure.yaml

  roles:
    - common
    - security
    - internetAccess
    - finalStuff

