---

- hosts: veopi
  remote_user: pi
  gather_facts: false
  vars_prompt:
  - name: gmailUser
    prompt: "\n\nPlease type valid gmail account for emails sending from raspberry"
    private: no

  - name: gmailPass
    prompt: "\n\nNow, that gmail password"

  - name: duckDnsToken
    prompt: "\n\nInsert your DuckDns token present at http://www.duckdns.org"
    private: no

  vars_files:
  - vars/piStuff.yaml

  roles:
    - common
    - security
    - internetAccess
    - finalStuff
