---

- hosts: raspi
  remote_user: pi

  vars_prompt:
  - name: pass
    prompt: Enter new raspberry pi password

  tasks:
  - debug: msg="Setting {{ pass }} as raspberryPi password"

  - name: Install additional software via apt
    become: yes
    local_action: command apt-get install -y whois

  - name: Encrypt password
    local_action: command mkpasswd --method=sha-512 {{ pass }}
    register: pass512

  - debug: msg="Setting {{ pass512.stdout }} as raspberryPi password"
  
  - name: Change pi password
    become: yes
    become_user: root
    user: name=pi password={{ pass512.stdout }} update_password=always

  - name: Change pi password at /etc/ansible/hosts
    become: yes
    become_user: root
    local_action: command sed -i 's/\(.*\)ansible_user=\(.*\) ansible_ssh_pass=\(.*\)/\1ansible_user=\2 ansible_ssh_pass={{ pass }}/g' /etc/ansible/hosts
