---
additional_packages:
  - cmake
  - git
  - imagemagick
  - jq
  - libcurl4-openssl-dev
  - libssl-dev
  - libxml2
  - libxml2-dev
  - openssl
  - pinentry-curses
  - pkg-config
  - stress
  - stress
  - telnet
  - vim
  - wget
  - whois
  - xclip
  
toCleanDirectories:
  - Documents
  - Documentos
  - Music
  - Música
  - Pictures
  - Imágenes
  - Public
  - Público
  - Templates
  - Plantillas
  - Videos
  - Vídeos
  - Bookshelf
  - MagPi
  - python_games
