---
local_additional_packages:
  - stress
  - whois
  - cmake
  - libcurl4-openssl-dev
  - libssl-dev
  - libxml2
  - libxml2-dev
  - openssl
  - pinentry-curses
  - pkg-config
  - xclip
  
lpass:
  version: 1.3.1
  url: https://github.com/lastpass/lastpass-cli/releases/download/v1.3.1/lastpass-cli-1.3.1.tar.gz
