---
- name: Install software via apt
  become: yes
  apt:
    name: '{{ additional_packages }}'

- name: Load gmail credentials from file
  shell: cat /home/pi/.gmailUser
  register: gmailUserReaded

- name: Load gmail password from file
  shell: cat /home/pi/.gmailPass
  register: gmailPassReaded

- name: Add gmail account to ssmtp.conf
  become: yes
  blockinfile:
    path: /etc/ssmtp/ssmtp.conf
    create: yes
    block: |
      root=postmaster
      mailhub=smtp.gmail.com:587
      hostname={{ pi.hostname }}
      AuthUser={{ gmailUserReaded.stdout }}
      AuthPass={{ gmailPassReaded.stdout }}
      FromLineOverride=YES
      UseSTARTTLS=YES

- name: Clean monit conf-enabled
  become: yes
  file:
    state: absent
    path: /etc/monit/conf-enabled

- name: Clean monit conf-available
  become: yes
  file:
    state: absent
    path: /etc/monit/conf-available

- name: Configure monit timeout
  become: yes
  lineinfile:
    path: /etc/monit/monitrc
    regexp: '^  set daemon'
    line: '  set daemon {{ monitTimeout}}'

- name: Setup monit conf
  become: yes
  blockinfile:
    path: /etc/monit/monitrc
    create: yes
    block: |
      #Mail settings
      set mail-format {
        from: monit@raspberry.pi
        subject: Monit Alert - $SERVICE
        message:
        Date:        $DATE
        Host:        $HOST
        $DESCRIPTION

                 Your faithful employee,
                 Monit }
      set mailserver smtp.gmail.com port 587
        username {{ gmailUserReaded.stdout }} password "{{ gmailPassReaded.stdout }}"
        using TLSV1 with timeout 30 seconds
      set alert {{ gmailUserReaded.stdout }}

- name: Disable conf-enabled folder configurations
  become: yes
  lineinfile:
    path: /etc/monit/monitrc
    state: absent
    line: 'include /etc/monit/conf-enabled/*'

- name: Add ssh login monit alert
  become: yes
  blockinfile:
    path: /etc/monit/conf.d/sshAccesses.conf
    create: yes
    block: |
      check file ssh_logins with path /var/log/auth.log
        if match "session opened" then alert
        if match "authentication failures" then alert

- name: Make sure monit is enabled and restarted
  become: yes
  service:
    name: monit
    state: restarted 
    enabled: yes 
  when: production_mode

- name: Disable and stop monit if no production mode
  become: yes
  service:
    name: monit
    state: stopped 
    enabled: no
  when: not production_mode
