---

- name: Install additional software via apt
  become: yes
  apt:
    name: "{{ additional_packages }}"
    force: yes
    update_cache: yes
    state: latest

- name: Add gmail account to ssmtp.conf
  become: yes
  blockinfile:
    path: /etc/ssmtp/ssmtp.conf
    create: yes
    block: |
      root=postmaster
      mailhub=smtp.gmail.com:587
      hostname=raspberrypi
      AuthUser={{ gmailUser }}
      AuthPass={{ gmailPass }}
      FromLineOverride=YES
      UseSTARTTLS=YES

- name: Clean monit conf-enabled
  become: yes
  file:
    state: absent
    path: /etc/monit/conf-enabled

- name: Clean monit conf-available
  become: yes
  file:
    state: absent
    path: /etc/monit/conf-available

- name: Configure monit timeout
  become: yes
  lineinfile:
    path: /etc/monit/monitrc
    regexp: '^  set daemon'
    line: '  set daemon {{ monitTimeout}}'

- name: Setup monit conf
  become: yes
  blockinfile:
    path: /etc/monit/monitrc
    create: yes
    block: |
      #Mail settings
      set mail-format {
        from: monit@raspberry.pi
        subject: Monit Alert - $SERVICE
        message:
        Date:        $DATE
        Host:        $HOST
        $DESCRIPTION

                 Your faithful employee,
                 Monit }
      set mailserver smtp.gmail.com port 587
        username {{ gmailUser }} password "{{ gmailPass}}"
        using TLSV1 with timeout 30 seconds
      set alert emonterodelrio@gmail.com

- name: Copy conf to jail.conf
  shell: awk '{ printf "# "; print; }' /etc/fail2ban/jail.conf | sudo tee /etc/fail2ban/jail.local
 
- name: Configure fail2ban
  become: yes
  blockinfile:
    path: /etc/fail2ban/jail.local
    block: |
      [DEFAULT]
      ignoreip = 127.0.0.1/8
      bantime = {{ fail2ban.bantime }}
      findtime = {{ fail2ban.findtime }}
      maxretry = {{ fail2ban.maxretry }}

- name: Add ssh login monit alert
  become: yes
  blockinfile:
    path: /etc/monit/conf.d/sshAccesses.conf
    create: yes
    block: |
      check file ssh_logins with path /var/log/auth.log
        if match "session opened" then alert
        if match "authentication failures" then alert

- name: Make sure monit is enabled and restarted
  become: yes
  service:
    name: monit
    state: restarted 
    enabled: yes 

- name: Reboot server
  shell: "sleep 5 && reboot"
  async: 1
  poll: 0
  when: reboot_system

- name: Wait for reboot
  wait_for_connection:
    connect_timeout: 10
    sleep: 2
    delay: 3
    timeout: 300
  when: reboot_system
