---

additional_packages:
  - nginx=1.10.3-1+deb9u2
  - openssl

nginx:
  worker_processes: 4
  worker_connections: 1024
  keepalive_timeout: 65
  noSSLport: 80
  antiddos:
    zonesizemb: 10  #Tamaño máximo de zona
    maxreqsec: 30   #Máximo peticiones por segundo
    maxburst: 15    #Máximo de ráfagas
