---
- name: Install software via apt
  become: yes
  apt:
    name: '{{ additional_packages }}'
  when: DHT22.present

- name: Download adafruit library
  git:
    repo: 'https://github.com/adafruit/Adafruit_Python_DHT.git'
    dest: "{{ DHT22.path }}/Adafruit_Python_DHT"
  when: DHT22.present

- name: Install adafruit library
  become: yes
  shell: cd {{ DHT22.path }}/Adafruit_Python_DHT && python setup.py install
  when: DHT22.present
  
- name: Ensure numpy
  become: yes
  shell: pip install numpy
  when: DHT22.present

- name: Create folders
  become: yes
  file:
    path: "{{ item }}"
    owner: pi
    group: pi
    mode: 0755
    state: directory
  with_items:
    - "{{ meteoUpdatePicturesPath }}"
    - "{{ DHT22.path }}"
  when: DHT22.present

- name: Setup dht22 script
  template:
    src: dht22.j2
    dest: "{{ DHT22.path }}/dht22.py"
    mode: 0777
  when: DHT22.present

- name: Setup meteo-update-pictures script
  template:
    src: updateMeteoPic.sh
    dest: "{{ meteoUpdatePicturesPath }}/updateMeteoPic.sh"
    mode: 0777
  when: DHT22.present
  
- name: Setup dht22 stop script
  template:
    src: stop_dht22.j2
    dest: "{{ DHT22.path }}/stop_dht22.sh"
    mode: 0777
  when: DHT22.present

- name: Setup stop meteo-update-pictures script
  template:
    src: stopUpdateMeteoPic.sh
    dest: "{{ meteoUpdatePicturesPath }}/stopUpdateMeteoPic.sh"
    mode: 0777
  when: DHT22.present

- name: Stop dht22 script
  become: yes
  shell: "{{ DHT22.path }}/stop_dht22.sh"
  ignore_errors: yes
  when: DHT22.present

- name: Stop meteo-update-pictures script
  become: yes
  shell: "{{ meteoUpdatePicturesPath }}/stopUpdateMeteoPic.sh"
  ignore_errors: yes
  when: DHT22.present

- name: Stop dht22 script every night
  become: yes
  become_user: root
  cron:
    name: "Stop dht22 script"
    minute: "58"
    hour: "23"
    job: "{{ DHT22.path }}/stop_dht22.sh"

- name: Crontab DHT22 scripts
  cron:
    name: "dht22"
    minute: "*"
    hour: "*"
    day: "*"
    month: "*"
    weekday: "*" 
    job: "bash -c 'if [ ! \"$(ps aux | grep dht22.py | grep -v grep)\" ]; then nohup {{ DHT22.path }}/dht22.py &>> {{ DHT22.path }}/dht22.log& fi'"
  when: DHT22.present

- name: Crontab meteo-update-pictures script
  cron:
    name: "UpdateMeteoPictures"
    minute: "0"
    hour: "*"
    day: "*"
    month: "*"
    weekday: "*" 
    job: "bash -c 'nohup {{ meteoUpdatePicturesPath }}/updateMeteoPic.sh &>> {{ meteoUpdatePicturesPath }}/updateMeteoPic.log&'"
  when: DHT22.present

- name: Setup dht22 logrotate.d
  become: yes
  template:
    src: logrotate_dht22.j2
    dest: "/etc/logrotate.d/dht22"
    mode: 0644
    owner: root
    group: root
  when: DHT22.present

- name: Setup updateMeteoPic logrotate.d
  become: yes
  template:
    src: logrotate_updateMeteoPic.j2
    dest: "/etc/logrotate.d/updateMeteoPic"
    mode: 0644
    owner: root
    group: root
  when: DHT22.present
