---
- name: Create DHT22 folder
  file:
    path: "{{ DHT22.path }}"
    owner: pi
    group: pi
    state: directory
  when: DHT22.present

- name: Install software via apt
  become: yes
  shell: apt-get install -y {{ item }}
  with_items: "{{ additional_packages }}"
  when: DHT22.present

- name: Download adafruit library
  git:
    repo: 'https://github.com/adafruit/Adafruit_Python_DHT.git'
    dest: "{{ DHT22.path }}/Adafruit_Python_DHT"
  when: DHT22.present

- name: Install adafruit library
  become: yes
  shell: cd {{ DHT22.path }}/Adafruit_Python_DHT && python setup.py install
  when: DHT22.present

- name: Setup DHT22 scripts
  template:
    src: dht22.j2
    dest: "{{ DHT22.path }}/dht22.py"
    mode: 0777
  when: DHT22.present

- name: Stop all scripts
  become: yes
  shell: "for i in $(ps aux | grep \"{{ DHT22.path }}\" | grep -v \"color=auto\" | awk '{print $2}');do kill -9 $i; done"
  ignore_errors: yes  

- name: Crontab DHT22 scripts
  cron:
    name: "dht22"
    minute: "*"
    hour: "*"
    day: "*"
    month: "*"
    weekday: "*" 
    job: "bash -c 'if [ ! \"$(ps aux | grep dht22.py | grep -v grep)\" ]; then cd {{ DHT22.path }} && nohup ./dht22.py &>> {{ DHT22.path }}/dht22.log& fi'"
  when: DHT22.present
