---
- name: Install software via apt
  become: yes
  apt:
    name: '{{ additional_packages }}'
  when: DHT22.present

- name: Download adafruit library
  git:
    repo: 'https://github.com/adafruit/Adafruit_Python_DHT.git'
    dest: "{{ DHT22.path }}/Adafruit_Python_DHT"
  when: DHT22.present

- name: Install adafruit library
  become: yes
  shell: cd {{ DHT22.path }}/Adafruit_Python_DHT && python setup.py install
  when: DHT22.present
  
- name: Ensure numpy
  become: yes
  shell: pip install numpy
  when: DHT22.present

- name: Create folders
  become: yes
  file:
    path: "{{ item }}"
    owner: pi
    group: pi
    mode: 0755
    state: directory
  with_items:
    - "{{ DHT22.path }}"
  when: DHT22.present

- name: Setup dht22_taps script
  template:
    src: dht22_taps.j2
    dest: "{{ DHT22.path }}/dht22_taps.py"
    mode: 0777
  when: DHT22.present
  
- name: Setup dht22_heating script
  template:
    src: dht22_heating.j2
    dest: "{{ DHT22.path }}/dht22_heating.py"
    mode: 0777
  when: DHT22.present

- name: Setup dht22 stop script
  template:
    src: stop_dht22.j2
    dest: "{{ DHT22.path }}/stop_dht22.sh"
    mode: 0777
  when: DHT22.present

- name: Stop dht22 script
  become: yes
  shell: "{{ DHT22.path }}/stop_dht22.sh"
  ignore_errors: yes
  when: DHT22.present

- name: Crontab DHT22 scripts
  cron:
    name: "dht22_{{ item }}"
    minute: "*"
    hour: "*"
    day: "*"
    month: "*"
    weekday: "*" 
    job: "bash -c 'if [ ! \"$(ps aux | grep dht22_{{ item }}.py | grep -v grep)\" ]; then nohup {{ DHT22.path }}/dht22_{{ item }}.py &>> {{ DHT22.path }}/dht22_{{ item }}.log& fi'"
  with_items:
    - "taps"
    - "heating"
  when: DHT22.present

- name: Setup dht22 logrotate.d
  become: yes
  template:
    src: logrotate_dht22.j2
    dest: "/etc/logrotate.d/dht22_{{ item }}"
    mode: 0644
    owner: root
    group: root
  with_items:
    - "taps"
    - "heating"
  when: DHT22.present
