---
- name: Make sure fail2ban is enabled and restarted
  become: yes
  service:
    name: fail2ban
    state: restarted 
    enabled: yes 
  when: production_mode

- name: Disable and stop fail2ban if no production mode
  become: yes
  service:
    name: fail2ban
    state: stopped 
    enabled: no
  when: not production_mode

- name: Make sure monit is enabled and restarted
  become: yes
  service:
    name: monit
    state: restarted 
    enabled: yes 
  when: production_mode

- name: Disable and stop monit if no production mode
  become: yes
  service:
    name: monit
    state: stopped 
    enabled: no
  when: not production_mode
