---
- name: Update all packages to the latest version
  apt:
    upgrade: dist

- name: Update all packages to the latest version
  apt:
    name: "*"
    state: latest

- name: Setup fixed ip
  become: yes
  blockinfile:
    path: /etc/dhcpcd.conf
    block: |
      interface eth0

      static ip_address={{ pi.network.ip }}/{{ pi.network.maskLength }}
      static routers={{ pi.network.prefix }}.1
      static domain_name_servers=8.8.8.8 8.8.4.4

      interface wlan0

      static ip_address={{ pi.network.ip }}/{{ pi.network.maskLength }}
      static routers={{ pi.network.prefix }}.1
      static domain_name_servers=8.8.8.8 8.8.4.4

- name: Setup dns
  become: yes
  blockinfile:
    path: /etc/resolv.conf
    block: |
      nameserver 8.8.8.8
      nameserver 8.8.4.4

- name: Change pi ip at /etc/ansible/hosts
  become: yes
  become_user: root
  local_action: command sed -i 's/\(.*\) ansible_user=\(.*\)/{{ pi.network.ip }} ansible_user=\2/g' /etc/ansible/hosts

- name: Delete unused stuff
  file:
   path: "{{item}}"
   state: absent
  with_items: "{{ toCleanDirectories }}"

- name: Common - Reboot server
  shell: "sleep 5 && reboot"
  async: 1
  poll: 0

- name: Common - Wait for reboot
  wait_for_connection:
    connect_timeout: 10
    sleep: 2
    delay: 3
    timeout: 300
