---
- name: Install software via apt
  become: yes
  apt:
    name: '{{ additional_packages }}'

- name: Update all packages to the latest version
  become: yes
  shell: apt-get update

- name: Setup alias at bash_profile
  become: yes
  lineinfile:
    path: /etc/bash.bashrc
    line: "{{ item }}"
  with_items:
    - alias ll='ls -larth'

- name: Delete history stuff from pi user
  become: yes
  lineinfile:
    path: /home/pi/.bashrc
    state: absent
    regexp: '^HIST'

- name: Setup history at /etc/bash.bashrc
  become: yes
  lineinfile:
    path: /etc/bash.bashrc
    line: "{{ item }}"
  with_items:
    - HISTCONTROL=ignoreboth:erasedups
    - HISTSIZE=100000
    - HISTFILESIZE=200000

- name: Swappiness to {{ pi.swappiness }} at /etc/sysctl.conf
  become: yes
  lineinfile:
    path: /etc/sysctl.conf
    line: "vm.swappiness = {{ pi.swappiness }}"
    state: present
    regexp: '^vm.swappiness'

- name: Enable bluetooth at /boot/config.txt
  become: yes
  lineinfile:
    path: /boot/config.txt
    line: "dtoverlay=pi3-disable-bt"
    regexp: '^dtoverlay'
    state: present
  when: pi.bluetoothEnabled

- name: Disable bluetooth at /boot/config.txt
  become: yes
  lineinfile:
    path: /boot/config.txt
    regexp: '^dtoverlay'
    state: absent
  when: not pi.bluetoothEnabled

- name: Change hostname
  become: yes
  shell: echo {{ pi.hostname }} > /etc/hostname

- name: Change etc hosts
  become: yes
  shell: sed -i "s/raspberrypi/{{ pi.hostname }}/g" /etc/hosts

- name: Setup fixed ip
  become: yes
  blockinfile:
    path: /etc/dhcpcd.conf
    block: |
      interface eth0

      static ip_address={{ pi.network.ip }}/{{ pi.network.maskLength }}
      static routers={{ pi.network.prefix }}.1
      static domain_name_servers={{ pi.network.dns1 }} {{ pi.network.dns2 }}

      interface wlan0

      static ip_address={{ pi.network.ip }}/{{ pi.network.maskLength }}
      static routers={{ pi.network.prefix }}.1
      static domain_name_servers={{ pi.network.dns1 }} {{ pi.network.dns2 }}
  register: changeIp

- name: Setup dns
  become: yes
  blockinfile:
    path: /etc/resolv.conf
    block: |
      nameserver {{ pi.network.dns1 }}
      nameserver {{ pi.network.dns2 }}

- name: Change pi ip at /etc/ansible/hosts
  become: yes
  become_user: root
  local_action: command sed -i 's/\(.*\) ansible_user=\(.*\)/{{ pi.network.ip }} ansible_user=\2/g' /etc/ansible/hosts

- name: Delete previous known_hosts user
  local_action: command ssh-keygen -f "/home/emontero/.ssh/known_hosts" -R {{ pi.network.ip }}
  ignore_errors: yes

- name: Delete previous known_hosts root
  become: yes
  become_user: root
  local_action: command ssh-keygen -f "/home/emontero/.ssh/known_hosts" -R {{ pi.network.ip }}
  ignore_errors: yes

- name: Delete unused stuff
  file:
   path: "{{item}}"
   state: absent
  with_items: "{{ toCleanDirectories }}"

- name: Reboot raspi
  become: yes
  shell: sudo reboot -h now
