---
- name: Create metric collectors folder
  file:
    path: "{{ metricsCollectors.path }}"
    owner: pi
    group: pi
    state: directory

- name: Create metric collectors log folder
  file:
    path: "{{ metricsCollectors.path }}/logs"
    owner: pi
    group: pi
    state: directory

- name: Create metric groups log folder
  file:
    path: "{{ metricsCollectors.path }}/logs/{{ item.group }}"
    owner: pi
    group: pi
    state: directory
  with_items: "{{ collectors }}"

- name: Setup scripts
  template:
    src: collectMetrics.j2
    dest: "{{ metricsCollectors.path }}/{{ item.group }}_{{ item.name }}.sh"
    mode: 0777
  with_items: "{{ collectors }}"

- name: Setup stop script
  template:
    src: stop_collectors.j2
    dest: "{{ metricsCollectors.path }}/stop_collectors.sh"
    mode: 0777

- name: Stop all scripts
  become: yes
  shell: "{{ metricsCollectors.path }}/stop_collectors.sh"
  ignore_errors: yes

- name: Crontab scripts
  cron:
    name: "{{ item.group }}_{{ item.name }}"
    minute: "*"
    hour: "*"
    day: "*"
    month: "*"
    weekday: "*"
    job: "bash -c 'if [ ! \"$(ps aux | grep {{ item.group }}_{{ item.name }}.sh | grep -v grep)\" ]; then nohup {{ metricsCollectors.path }}/{{ item.group }}_{{ item.name }}.sh &>> {{ metricsCollectors.path }}/logs/{{ item.group }}/{{ item.name }}.log& fi'"
  with_items: "{{ collectors }}"
