---
- name: Create metric collectors folder
  file:
    path: "{{ metricsCollectors.path }}"
    owner: pi
    group: pi
    state: directory

- name: Setup scripts
  template:
    src: collectMetrics.j2
    dest: "{{ metricsCollectors.path }}/{{ item.measureName }}.sh"
    mode: 0777
  with_items: "{{ collectors }}"

- name: Crontab scripts
  cron:
    name: "{{ item.measureName }}"
    minute: "{{ item.crontab.split(' ')[0] }}"
    hour: "{{ item.crontab.split(' ')[1] }}"
    day: "{{ item.crontab.split(' ')[2] }}"
    month: "{{ item.crontab.split(' ')[3] }}"
    weekday: "{{ item.crontab.split(' ')[4] }}"  
    job: "{{ metricsCollectors.path }}/{{ item.measureName }}.sh >/dev/null 2>&1"
  with_items: "{{ collectors }}"
