---
- name: Create metric collectors folder
  file:
    path: "{{ metricsCollectors.path }}"
    owner: pi
    group: pi
    state: directory

- name: Create metric collectors log folder
  file:
    path: "{{ metricsCollectors.path }}/logs"
    owner: pi
    group: pi
    state: directory

- name: Setup scripts
  template:
    src: collectMetrics.j2
    dest: "{{ metricsCollectors.path }}/{{ item.measureName }}.sh"
    mode: 0777
  with_items: "{{ collectors }}"

- name: Stop all scripts
  shell: "for i in $(ps aux | grep \"{{ metricsCollectors.path }}\" | grep -v \"color=auto\" | awk '{print $2}');do sudo kill -9 $i; done"
  ignore_errors: yes

- name: Crontab scripts
  cron:
    name: "{{ item.measureName }}"
    minute: "*"
    hour: "*"
    day: "*"
    month: "*"
    weekday: "*"
    job: "bash -c 'if [ ! \"$(ps aux | grep {{ item.measureName }}.sh | grep -v grep)\" ]; then nohup {{ metricsCollectors.path }}/{{ item.measureName }}.sh &>> {{ metricsCollectors.path }}/logs/{{ item.measureName }}.log& fi'"
  with_items: "{{ collectors }}"
