---
metricsCollectors:
  path: /home/pi/metricsCollectors

collectors:
##   Pi Internals   ############################################################

##@@@   anomalous situations

  - name: reboots
    group: monitor
    command: "myDate=$(date \"+%b %-d\");myDate=\"${myDate^}\";grep -a \"$myDate\" /var/log/syslog | grep -a \"Booting Linux on physical\" | wc -l"
    delay: "*"

##@@@   temperatures

  - name: cpu
    group: temperature
    command: "cpuTemp0=$(cat /sys/class/thermal/thermal_zone0/temp);cpuTemp1=$(($cpuTemp0/1000));cpuTemp2=$(($cpuTemp0/100));cpuTempM=$(($cpuTemp2 % $cpuTemp1));echo $cpuTemp1\".\"$cpuTempM"
    delay: "*"

  - name: gpu
    group: temperature
    command: "vcgencmd measure_temp | cut -d\"=\" -f2 | cut -d\"'\" -f1"
    delay: "*"

##@@@   voltages

  - name: core
    group: voltage
    command: "vcgencmd measure_volts core | cut -d\"=\" -f2 | cut -d'V' -f1"
    delay: "*"

  - name: sdram_c
    group: voltage
    command: "vcgencmd measure_volts sdram_c | cut -d\"=\" -f2 | cut -d'V' -f1"
    delay: "*"

  - name: sdram_i
    group: voltage
    command: "vcgencmd measure_volts sdram_i | cut -d\"=\" -f2 | cut -d'V' -f1"
    delay: "*"

  - name: sdram_p
    group: voltage
    command: "vcgencmd measure_volts sdram_p | cut -d\"=\" -f2 | cut -d'V' -f1"
    delay: "*"

##@@@   cpu

  - name: load_1
    group: cpu
    command: "cat /proc/loadavg | awk '{print $1}'"
    delay: "*"

  - name: load_5
    group: cpu
    command: "cat /proc/loadavg | awk '{print $2}'"
    delay: "*"

  - name: load_15
    group: cpu
    command: "cat /proc/loadavg | awk '{print $3}'"
    delay: "*"

##@@@   memory
  - name: used_percent
    group: memory
    command: "free -m | grep Mem | awk '{userPercent=$3/$2}; {split(userPercent,a,\".\"); print a[1]\".\"substr(a[2],1,2)}'"
    delay: "*"

  - name: total
    group: memory
    command: "free -m | grep -i mem | awk '{print $2}'"
    delay: "*"

  - name: used
    group: memory
    command: "free -m | grep -i mem | awk '{print $3}'"
    delay: "*"

  - name: free
    group: memory
    command: "free -m | grep -i mem | awk '{print $4}'"
    delay: "*"

  - name: shared
    group: memory
    command: "free -m | grep -i mem | awk '{print $5}'"
    delay: "*"

  - name: buff_cache
    group: memory
    command: "free -m | grep -i mem | awk '{print $6}'"
    delay: "*"

  - name: available
    group: memory
    command: "free -m | grep -i mem | awk '{print $7}'"
    delay: "*"

##@@@   swap

  - name: total
    group: swap
    command: "free -m | grep -i swap | awk '{print $2}'"
    delay: "*"

  - name: used
    group: swap
    command: "free -m | grep -i swap | awk '{print $3}'"
    delay: "*"

  - name: free
    group: swap
    command: "free -m | grep -i swap | awk '{print $4}'"
    delay: "*"

##@@@   disk

  - name: used_percent
    group: disk
    command: "sleep 10 && echo \"0.$(expr \"$(df -h | grep \"/dev/root\" | awk '{print $5}' | tr -d \"%\")\")\""
    delay: "*"

  - name: total_KB
    group: disk
    command: "sleep 10 && df |grep \"/dev/root\" | awk '{print $2}'"
    delay: "*"

  - name: used_KB
    group: disk
    command: "sleep 10 && df |grep \"/dev/root\" | awk '{print $3}'"
    delay: "*"

  - name: free_KB
    group: disk
    command: "sleep 10 && df |grep \"/dev/root\" | awk '{print $4}'"
    delay: "*"


##   Security   ############################################################

##@@@   sessions

  - name: current_sessions
    group: sessions
    command: "ps aux | grep -a ssh | grep -v \"grep\\|metricsCollectors\\|/sshd\" | grep @ | wc -l"
    delay: "*"

##@@@   ssh

  - name: login_ok
    group: ssh
    command: "myDate=$(date \"+%b %-d\");myDate=\"${myDate^}\";grep -a \"$myDate\" /var/log/auth.log | grep -a sshd | grep -a \"session opened for user\" | wc -l"
    delay: "*"

  - name: login_ko
    group: ssh
    command: "myDate=$(date \"+%b %-d\");myDate=\"${myDate^}\";grep -a \"$myDate\" /var/log/auth.log | grep -a sshd | grep -a \"authentication failure\" | wc -l"
    delay: "*"

##   Network   ############################################################

  - name: established
    group: network
    command: "sleep 20 && sudo netstat -putan | grep ESTABLISHED | wc -l"
    delay: "*"

  - name: listen
    group: network
    command: "sleep 20 && sudo netstat -putan | grep LISTEN | wc -l"
    delay: "*"
  
##@@@   nginx

  - name: external_acceses
    group: nginx
    command: "sleep 20 && myDate=$(date \"+%-d/%b\");myDate=\"${myDate^}\";grep -a \"$myDate\" {{ nginx.log.access.path }} | grep -v \"{{ pi.network.prefix }}\" | wc -l"
    delay: "*"

  - name: local_acceses
    group: nginx
    command: "sleep 20 && myDate=$(date \"+%-d/%b\");myDate=\"${myDate^}\";grep -a \"$myDate\" {{ nginx.log.access.path }} | grep \"{{ pi.network.prefix }}\" | wc -l"
    delay: "*"

  - name: get
    group: nginx
    command: "sleep 20 && myDate=$(date \"+%-d/%b\");myDate=\"${myDate^}\";grep -a \"$myDate\" {{ nginx.log.access.path }} | awk '{print $1 \" \" $4}' | tr -d \"-\"  | tr -d \"\\\"\" | grep GET | wc -l"
    delay: "*"

  - name: post
    group: nginx
    command: "sleep 20 && myDate=$(date \"+%-d/%b\");myDate=\"${myDate^}\";grep -a \"$myDate\" {{ nginx.log.access.path }} | awk '{print $1 \" \" $4}' | tr -d \"-\"  | tr -d \"\\\"\" | grep POST | wc -l"
    delay: "*"

  - name: put
    group: nginx
    command: "sleep 20 && myDate=$(date \"+%-d/%b\");myDate=\"${myDate^}\";grep -a \"$myDate\" {{ nginx.log.access.path }} | awk '{print $1 \" \" $4}' | tr -d \"-\"  | tr -d \"\\\"\" | grep PUT | wc -l"
    delay: "*"

  - name: other
    group: nginx
    command: "sleep 20 && myDate=$(date \"+%-d/%b\");myDate=\"${myDate^}\";grep -a \"$myDate\" {{ nginx.log.access.path }} | awk '{print $1 \" \" $4}' | tr -d \"-\"  | tr -d \"\\\"\" | grep -v \"POST\\|GET\\|PUT\" | wc -l"
    delay: "*"