---
metricsCollectors:
  path: /home/pi/metricsCollectors


collectors:
##   Pi Internals   ############################################################
  - name: cpu
    group: temperature
    command: "cpuTemp0=$(cat /sys/class/thermal/thermal_zone0/temp);cpuTemp1=$(($cpuTemp0/1000));cpuTemp2=$(($cpuTemp0/100));cpuTempM=$(($cpuTemp2 % $cpuTemp1));echo $cpuTemp1\".\"$cpuTempM"
    delay: "1"

  - name: gpu
    group: temperature
    command: "/opt/vc/bin/vcgencmd measure_temp | cut -d\"=\" -f2 | cut -d\"'\" -f1"
    delay: "1"

  - name: core
    group: voltage
    command: "vcgencmd measure_volts core | cut -d\"=\" -f2 | cut -d'V' -f1"
    delay: "1"

  - name: sdram_c
    group: voltage
    command: "vcgencmd measure_volts sdram_c | cut -d\"=\" -f2 | cut -d'V' -f1"
    delay: "1"

  - name: sdram_i
    group: voltage
    command: "vcgencmd measure_volts sdram_i | cut -d\"=\" -f2 | cut -d'V' -f1"
    delay: "1"

  - name: sdram_p
    group: voltage
    command: "vcgencmd measure_volts sdram_p | cut -d\"=\" -f2 | cut -d'V' -f1"
    delay: "1"

  - name: load_1
    group: cpu
    command: "cat /proc/loadavg | awk '{print $1}'"
    delay: "60"

  - name: load_5
    group: cpu
    command: "cat /proc/loadavg | awk '{print $2}'"
    delay: "60"

  - name: load_15
    group: cpu
    command: "cat /proc/loadavg | awk '{print $3}'"
    delay: "60"

  - name: used_percent
    group: memory
    command: "free -m | grep Mem | awk '{userPercent=$3/$2}; {split(userPercent,a,\".\"); print a[1]\".\"substr(a[2],1,2)}'"
    delay: "60"

  - name: total
    group: memory
    command: "free -m | grep -i mem | awk '{print $2}'"
    delay: "60"

  - name: used
    group: memory
    command: "free -m | grep -i mem | awk '{print $3}'"
    delay: "60"

  - name: free
    group: memory
    command: "free -m | grep -i mem | awk '{print $4}'"
    delay: "60"

  - name: shared
    group: memory
    command: "free -m | grep -i mem | awk '{print $5}'"
    delay: "60"

  - name: buff_cache
    group: memory
    command: "free -m | grep -i mem | awk '{print $6}'"
    delay: "60"

  - name: available
    group: memory
    command: "free -m | grep -i mem | awk '{print $7}'"
    delay: "60"

  - name: total
    group: swap
    command: "free -m | grep -i swap | awk '{print $2}'"
    delay: "60"

  - name: used
    group: swap
    command: "free -m | grep -i swap | awk '{print $3}'"
    delay: "60"

  - name: free
    group: swap
    command: "free -m | grep -i swap | awk '{print $4}'"
    delay: "60"

  - name: used_percent
    group: disk
    command: "echo \"0.$(expr \"$(df -h | grep \"/dev/root\" | awk '{print $5}' | tr -d \"%\")\")\""
    delay: "60"

  - name: total_KB
    group: disk
    command: "df |grep \"/dev/root\" | awk '{print $3}'"
    delay: "60"

  - name: used_KB
    group: disk
    command: "df |grep \"/dev/root\" | awk '{print $3}'"
    delay: "60"

  - name: free_KB
    group: disk
    command: "df |grep \"/dev/root\" | awk '{print $4}'"
    delay: "60"



##   Network   ############################################################

  - name: external_acceses
    group: nginx
    command: "cat /var/log/nginx/access.log  | grep -v \"{{ pi.network.prefix }}\" | grep \"$(date \"+%d\")\" | wc -l"
    delay: "60"

  - name: local_acceses
    group: nginx
    command: "cat /var/log/nginx/access.log  | grep \"{{ pi.network.prefix }}\" | grep \"$(date \"+%d\")\" | wc -l"
    delay: "60"

  - name: current_sessions
    group: sessions
    command: "who | wc -l"
    delay: "5"

  - name: login_ok
    group: ssh
    command: "LC_ALL=en_EN.utf8; month=$(date \"+%b\");month=\"${month^}\"; day=$(date \"+%-d\"); grep -e \"$month[[:blank:]]\\+$day\" /var/log/auth.log | grep ssh | grep \"session opened for user\" | wc -l"
    delay: "10"

  - name: login_ko
    group: ssh
    command: "LC_ALL=en_EN.utf8; month=$(date \"+%b\");month=\"${month^}\"; day=$(date \"+%-d\"); grep -e \"$month[[:blank:]]\\+$day\" /var/log/auth.log | grep ssh | grep \"authentication failure\" | wc -l"
    delay: "10"

##   Nginx   ############################################################

  - name: get
    group: nginx
    command: "LC_ALL=en_EN.utf8; cat /var/log/nginx/access.log | grep -e \"$(date \"+%d/%b\")\" | awk '{print $1 \" \" $4}' | tr -d \"-\"  | tr -d \"\\\"\" | grep GET | wc -l"
    delay: "60"

  - name: post
    group: nginx
    command: "LC_ALL=en_EN.utf8; cat /var/log/nginx/access.log | grep -e \"$(date \"+%d/%b\")\" | awk '{print $1 \" \" $4}' | tr -d \"-\"  | tr -d \"\\\"\" | grep POST | wc -l"
    delay: "60"

  - name: put
    group: nginx
    command: "LC_ALL=en_EN.utf8; cat /var/log/nginx/access.log | grep -e \"$(date \"+%d/%b\")\" | awk '{print $1 \" \" $4}' | tr -d \"-\"  | tr -d \"\\\"\" | grep PUT | wc -l"
    delay: "60"

  - name: other
    group: nginx
    command: "LC_ALL=en_EN.utf8; cat /var/log/nginx/access.log | grep -e \"$(date \"+%d/%b\")\" | awk '{print $1 \" \" $4}' | tr -d \"-\"  | tr -d \"\\\"\" | grep -v \"POST\\|GET\\|PUT\" | wc -l"
    delay: "60"

