---
- hosts: veopi
  gather_facts: true
  vars_prompt:

  - name: advisor
    prompt: "\n\nCAUTION! This will re-password your raspberry pi.\n\n\nFollowing variable prompts will be stored as hidden files inside /home/pi folder.\nIf you have enter any of them before you don't need to do it again (simply press enter), unless you want to change it.\nPress enter to continue"

  - name: piPass
    prompt: "\n\nInsert your raspberry pi new password"
    default: ""
    private: no

  vars_files:
    - ../vars/veopi.yaml

  roles:
    - storeAccounts
    - common