---
- hosts: meteopi
  gather_facts: true
  vars_files:
    - ../vars/meteopi.yaml

  roles:
    - autoHotSpot
    - duckDns
    - nginx
    - influxdb
    - metricsCollector
    - piCam
    - grafana
    - dht22
    - createMeteopiDash_Dht22
