---
- hosts: meteopi
  gather_facts: true
  vars_files:
  - ../vars/meteopi.yaml

  roles:
    # - security
    - duckDns
    - nginx
    - influxdb
    - metricsCollector
    - grafana
    - dht22
    - createMeteopiDash_Dht22
